backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  -name: "nextGame"
    label: "nextGame"
    folder: "content/featuredGames/nextGame"
    fields:
      - {label: "Gospodarz", name: "home", widget: "string"} 
      - {label: "Logo Gospodarz", name: "homeLogo", widget: "image"} 
      - {label: "Wynik", name: "result", widget: "string"} 
      - {label: "Logo Goscie", name: "awayLogo", widget: "image"} 
      - {label: "Goscie", name: "away", widget: "string"} 
      - {label: "Data", name: "date", widget: "date"} 
      - {label: "Godzina", name: "time", widget: "string"} 
      - {label: "Miejsce", name: "place", widget: "string"} 
  -name: "previousGame"
    label: "previousGame"
    folder: "content/featuredGames/previousGame"
    fields:
      - {label: "Gospodarz", name: "home", widget: "string"} 
      - {label: "Logo Gospodarz", name: "homeLogo", widget: "image"} 
      - {label: "Wynik", name: "result", widget: "string"} 
      - {label: "Logo Goscie", name: "awayLogo", widget: "image"} 
      - {label: "Goscie", name: "away", widget: "string"} 
      - {label: "Data", name: "date", widget: "date"} 
      - {label: "Godzina", name: "time", widget: "string"} 
      - {label: "Miejsce", name: "place", widget: "string"} 
