backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "src/images" # Media files will be stored in the repo under images/uploads
public_folder: "src/images"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "featuredGames"
    label: "Featured Games"
    folder: "content/featuredGames"
    fields:
      - {label: "Gospodarz Nastepny Mecz", name: "homeN", widget: "string"} 
      - {label: "Logo Gospodarz Nastepny Mecz", name: "homeLogoN", widget: "image"} 
      - {label: "Wynik Nastepny Mecz", name: "resultN", widget: "string"} 
      - {label: "Logo Goscie Nastepny Mecz", name: "awayLogoN", widget: "image"} 
      - {label: "Goscie Nastepny Mecz", name: "awayN", widget: "string"} 
      - {label: "Rozgrywki Następny Mecz", name: "leagueN", widget: "string"} 
      - {label: "Data Nastepny Mecz", name: "dateN", widget: "datetime"} 
      - {label: "Godzina Nastepny Mecz", name: "timeN", widget: "string"} 
      - {label: "Miejsce Nastepny Mecz", name: "placeN", widget: "string"} 
      - {label: "Gospodarz Poprzedni Mecz", name: "homeP", widget: "string"} 
      - {label: "Logo Gospodarz Poprzedni Mecz", name: "homeLogoP", widget: "image"} 
      - {label: "Wynik Poprzedni Mecz", name: "resultP", widget: "string"} 
      - {label: "Logo Goscie Poprzedni Mecz", name: "awayLogoP", widget: "image"} 
      - {label: "Goscie Poprzedni Mecz", name: "awayP", widget: "string"} 
      - {label: "Rozgrywki Poprzedni Mecz", name: "leagueP", widget: "string"}
      - {label: "Data Poprzedni Mecz", name: "dateP", widget: "datetime"} 
      - {label: "Godzina Poprzedni Mecz", name: "timeP", widget: "string"} 
      - {label: "Miejsce Poprzedni Mecz", name: "placeP", widget: "string"} 
  - name: "schedule"
    label: "Terminarz" 
    folder: "content/schedule" 
    create: true 
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Gospodarz", name: "home", widget: "string"}
      - {label: "Logo Gospodarz", name: "homeLogo", widget: "image"}
      - {label: "Wynik", name: "result", widget: "string"}
      - {label: "Goście", name: "away", widget: "string"}
      - {label: "Logo Goście", name: "awayLogo", widget: "image"}
      - {label: "Rozgrywki", name: "league", widget: "string"}
      - {label: "Kolejka", name: "leagueSub", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: false }
      - {label: "Godzina", name: "time", widget: "string"}
  - name: "sponsors"
    label: "Sponsorzy"
    folder: "content/sponsor"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Nazwa", name: "sponsorName", widget: "string"}
      - {label: "Logo", name: "sponsorLogo", widget: "image"}
  - name: "players"
    label: "Zawodnicy"
    folder: "content/players"
    create: true
    slug: "{{name}{surname}}"
    fields:
      - {label: "Imię", name: "name", widget: "string"}
      - {label: "Nazwisko", name: "surname", widget: "string"}
      - {label: "Pozycja", name: "position", widget: "string"}
      - {label: "Wiek", name: "age", widget: "number"}
      - {label: "Numer", name: "number", widget: "number"}
  - name: "juniorPlayers"
    label: "Drużyny Młodziżowe"
    folder: "content/juniorTeams"
    create: true
    slug: "{{name}-{section}}"
    fields:
      - {label: "Nazwa Drużyny", name: "name", widget: "string"}
      - {label: "Typ", name: "section", widget: "select", options: ["roster", "schedule"]}
      - {label: "Body", name: "body", widget: "markdown"}



      